<?xml version="1.0" encoding="UTF-8"?>
<definitions name="AsyncWeather" targetNamespace="http://j2ee.netbeans.org/wsdl/ProxyWeatherInfo/src/AsyncWeather"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/ProxyWeatherInfo/src/AsyncWeather" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types/>
    <message name="AsyncWeatherOperationRequest">
        <part name="IP_addressAsy" type="xsd:string"/>
        <part name="correlationId" type="xsd:string"/>
    </message>
    <portType name="AsyncWeatherPortType">
        <operation name="AsyncWeatherOperation">
            <input name="input1" message="tns:AsyncWeatherOperationRequest"/>
        </operation>
    </portType>
    <binding name="AsyncWeatherBinding" type="tns:AsyncWeatherPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="AsyncWeatherOperation">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/ProxyWeatherInfo/src/AsyncWeather"/>
            </input>
        </operation>
    </binding>
    <service name="AsyncWeatherService">
        <port name="AsyncWeatherPort" binding="tns:AsyncWeatherBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/AsyncWeatherService/AsyncWeatherPort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="AsyncWeather">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="AsyncWeatherPortTypeRole" portType="tns:AsyncWeatherPortType"/>
    </plnk:partnerLinkType>
</definitions>
