<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="geoipservice.asmxWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/geoipservice.asmxWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/geoipservice.asmxWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://www.webservicex.net/">
    <import location="http://www.webservicex.com/geoipservice.asmx?WSDL" namespace="http://www.webservicex.net/"/>
    <plnk:partnerLinkType name="GeoIPServiceSoapLinkType">
        <plnk:role name="GeoIPServiceSoapRole" portType="ns:GeoIPServiceSoap"/>
    </plnk:partnerLinkType>
</definitions>
